# Streamlit Secrets Configuration
# 
# This file is used as a template for Streamlit Cloud deployment.
# DO NOT commit actual API keys to version control.
# 
# For local development, use a .env file instead.
# For Streamlit Cloud deployment, set your secrets in the Streamlit Cloud dashboard.

# Google Generative AI API Key
# Obtain from: https://aistudio.google.com/
GOOGLE_API_KEY = "your-google-api-key-here"

# Example of other potential secrets (uncomment if needed)
# DATABASE_URL = "your-database-connection-string"
# OTHER_API_KEY = "your-other-api-key"